# Generated by Django 4.1.3 on 2022-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=280)),
                ('date', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
