# Generated by Django 4.1.4 on 2022-12-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
